from dataclasses import dataclass
import re
from .ast import (
    Function, ClassDecl, Field, VarDecl, Return, ExprStmt, If, While, DoWhile,
    For, Break, Continue, Throw, TryCatch, RawStmt, PackageDecl, PluginDecl,
    TemplateDecl, BlendDecl, RawDecl
)

@dataclass
class CodegenUnit:
    c_source: str
    target_arch: str

TYPE_MAP = {
    'Boolean':'int','boolean':'int','Bool':'int',
    'Char':'char','char':'char','Char16':'uint16_t','Char32':'uint32_t','Uchar':'unsigned char',
    'I16':'int16_t','I32':'int32_t','Int':'int32_t','I64':'int64_t',
    'U16':'uint16_t','U32':'uint32_t','U64':'uint64_t',
    'Float':'float','Double':'double','Ldouble':'long double',
    'Void':'void','void':'void','Type':'void*','Dynamic':'void*',
}

class NativeCodegen:
    def __init__(self, target_arch='native'):
        self.target_arch = target_arch
        self.known_classes = set()

    def emit(self, program, sema):
        self.known_classes = {d.name for d in program.declarations if isinstance(d, ClassDecl)}
        out = [
            '/* Generated by CMotive native codegen scaffold. */',
            f'/* target-arch: {self.target_arch} */',
            '#include <stdio.h>', '#include <stdlib.h>', '#include <stdint.h>', '#include <stddef.h>',
            '#include <string.h>', '#include <errno.h>', '',
            'typedef struct CMotiveVTable { void **slots; size_t count; } CMotiveVTable;',
            'typedef struct CMotiveObject { CMotiveVTable *vtable; } CMotiveObject;',
            'static void* CMotive_New(size_t n) { return calloc(1, n ? n : 1); }',
            'static void CMotive_Delete(void* p) { free(p); }',
            'static void CMotive_Throw(const char* msg) { fprintf(stderr, "CMotive exception: %s\\n", msg ? msg : "<null>"); exit(70); }',
            'static uint64_t CMOTIVE_ROTR64(uint64_t x, unsigned n) { n &= 63u; return n ? ((x >> n) | (x << (64u - n))) : x; }',
            'static uint64_t CMOTIVE_ROTL64(uint64_t x, unsigned n) { n &= 63u; return n ? ((x << n) | (x >> (64u - n))) : x; }',
            'static int cmotive_sys_file_exists(const char* p) { FILE *f = fopen(p, "rb"); if (!f) return 0; fclose(f); return 1; }',
            'static int cmotive_sys_logging_info(const char* m) { return fprintf(stdout, "%s\\n", m ? m : ""); }',
            'static int cmotive_sys_logging_error(const char* m) { return fprintf(stderr, "%s\\n", m ? m : ""); }',
            ''
        ]
        for d in program.declarations:
            if isinstance(d, ClassDecl):
                out += self.class_decl(d)
        for d in program.declarations:
            if isinstance(d, VarDecl) and d.global_decl:
                out += self.global_var(d)
        for d in program.declarations:
            if isinstance(d, Function):
                out += self.function(d)
            elif isinstance(d, ClassDecl):
                for m in d.methods:
                    if not m.pure_virtual:
                        out += self.function(m)
        if not any(isinstance(d, Function) and d.name == 'main' and not d.method_of for d in program.declarations):
            out += ['int main(void) { return 0; }', '']
        return CodegenUnit('\n'.join(out) + '\n', self.target_arch)

    def class_decl(self, c):
        lines = [f'typedef struct {c.name} {{', '  CMotiveObject __cmotive_base;']
        if c.base:
            lines.append(f'  /* single-inheritance base scaffold: {c.base} */')
        for f in c.fields:
            lines += self.field_decl(f)
        if c.has_virtuals:
            lines.append('  CMotiveVTable *__cmotive_vtable;')
        lines += [f'}} {c.name};', '']
        for n in c.nested:
            lines += self.class_decl(n)
        return lines

    def field_decl(self, f):
        if getattr(f, 'bit_fields', None):
            bits = ['  struct {']
            for count, name in f.bit_fields:
                bits.append(f'    unsigned int {self.safe_name(name)}:{int(count)};')
            bits.append(f'  }} {self.safe_name(f.name)};')
            return bits
        return ['  ' + self.c_decl(f.type_name, self.safe_name(f.name)) + ';']

    def global_var(self, v):
        return [self.c_decl(v.type_name, self.safe_name(v.name)) + ' = ' + self.expr(v.value, v.type_name) + ';', '']

    def safe_name(self, name):
        if not name:
            return '_cmotive_unnamed'
        name = name.replace('$','__')
        name = re.sub(r'\W', '_', name)
        if name in {'class','struct','void','int','long','short','switch','case','default','if','else','while','for','do','return','break','continue'}:
            return 'cmotive_' + name
        return name

    def c_name(self, f):
        if f.name == 'main' and not f.method_of:
            return 'main'
        if f.constructor:
            return f'{self.safe_name(f.method_of or f.name)}__ctor'
        if f.destructor:
            return f'{self.safe_name(f.method_of or f.name)}__dtor'
        return ((self.safe_name(f.method_of) + '__') if f.method_of else 'cmotive__') + self.safe_name(f.name)

    def c_decl(self, type_name, name):
        base, suffix = self.split_array_type(type_name)
        ctype = self.c_type(base)
        return f'{ctype} {name}{suffix}'

    def split_array_type(self, type_name):
        t = type_name or 'I32'
        arrays = ''.join(re.findall(r'\[[^\]]*\]', t))
        t = re.sub(r'\s*\[[^\]]*\]', '', t).strip()
        return t, arrays

    def c_type(self, type_name):
        if not type_name:
            return 'int32_t'
        t = type_name.replace('Const', 'const').replace('Volatile', 'volatile')
        # Preserve pointers and references in a C-compatible form.
        ptr = ''
        while t.endswith('*') or t.endswith('&'):
            ptr = ('*' if t[-1] == '*' else '*') + ptr
            t = t[:-1].strip()
        t = t.replace(' :: ', '::').replace('::', '_')
        parts = t.split()
        mapped = []
        for p in parts:
            mapped.append(TYPE_MAP.get(p, p))
        base = ' '.join(mapped) if mapped else 'int32_t'
        if base == 'void' and ptr:
            return 'void ' + ptr
        return (base + (' ' + ptr if ptr else '')).strip()

    def function(self, f):
        ret = 'void' if f.constructor or f.destructor else self.c_type(f.return_type)
        if f.name == 'main' and not f.method_of:
            ret = 'int'
        params = []
        if f.method_of:
            params.append(f'{self.safe_name(f.method_of)} *this')
        for p in f.params:
            params.append(self.c_decl(p.type_name, self.safe_name(p.name)))
        param_text = ', '.join(params) if params else 'void'
        lines = [f'{ret} {self.c_name(f)}({param_text}) {{']
        for s in f.body:
            lines += ['  ' + x for x in self.stmt(s)]
        if not any(isinstance(s, Return) for s in f.body):
            if ret == 'void':
                lines.append('  return;')
            else:
                lines.append('  return 0;')
        lines += ['}', '']
        return lines

    def stmt(self, s):
        if isinstance(s, VarDecl):
            return [self.local_var(s)]
        if isinstance(s, Return):
            return [f'return {self.expr(s.value)};' if s.value else 'return;']
        if isinstance(s, ExprStmt):
            return [self.expr_stmt(s.value)]
        if isinstance(s, If):
            out = [f'if ({self.expr(s.condition)}) {{']
            for x in s.then_body:
                out += ['  ' + y for y in self.stmt(x)]
            out.append('}')
            if s.else_body:
                out.append('else {')
                for x in s.else_body:
                    out += ['  ' + y for y in self.stmt(x)]
                out.append('}')
            return out
        if isinstance(s, While):
            out = [f'while ({self.expr(s.condition)}) {{']
            for x in s.body:
                out += ['  ' + y for y in self.stmt(x)]
            out.append('}')
            return out
        if isinstance(s, DoWhile):
            out = ['do {']
            for x in s.body:
                out += ['  ' + y for y in self.stmt(x)]
            out.append(f'}} while ({self.expr(s.condition)});')
            return out
        if isinstance(s, For):
            out = [f'for ({self.expr(s.header)}) {{']
            for x in s.body:
                out += ['  ' + y for y in self.stmt(x)]
            out.append('}')
            return out
        if isinstance(s, Break): return ['break;']
        if isinstance(s, Continue): return ['continue;']
        if isinstance(s, Throw): return [f'CMotive_Throw({self.stringish(s.value)});']
        if isinstance(s, TryCatch):
            out = ['/* CMotive Try/Catch scaffold: native unwinding is pending. */', '{']
            for x in s.try_body:
                out += ['  ' + y for y in self.stmt(x)]
            out.append('}')
            return out
        if isinstance(s, RawStmt): return [self.raw_stmt(s.value)]
        return ['/* unknown CMotive statement scaffold */']

    def local_var(self, s):
        name = self.safe_name(s.name)
        typ = s.type_name or 'I32'
        init = s.value or '0'
        # CMotive permits object variables and New.  The C bootstrap keeps value
        # objects zero-initialized and pointer objects dynamically allocated.
        base_typ = typ.replace('*','').strip()
        if re.search(r'\bNew\b', init):
            ctype = self.c_type(typ)
            if '*' in ctype:
                cls = base_typ or 'CMotiveObject'
                return f'{self.c_decl(typ, name)} = ({ctype})CMotive_New(sizeof({self.safe_name(cls)}));'
            return f'{self.c_decl(typ, name)} = {{0}};'
        if base_typ in self.known_classes and init in {'', '0'}:
            return f'{self.c_decl(typ, name)} = {{0}};'
        return f'{self.c_decl(typ, name)} = {self.expr(init, typ)};'

    def expr_stmt(self, text):
        e = self.expr(text)
        if not e or e == ';':
            return ';'
        return e if e.rstrip().endswith(';') else e + ';'

    def raw_stmt(self, text):
        e = self.translate_keywords(text)
        e = self.expr(e)
        return e if e.rstrip().endswith(';') or e.rstrip().endswith('}') else e + ';'

    def stringish(self, text):
        e = self.expr(text)
        if e.startswith('"'):
            return e
        return '"CMotive exception"'

    def expr(self, e, declared_type=None):
        if e is None:
            return ''
        s = str(e).strip()
        if not s:
            return ''
        s = self.translate_keywords(s)
        s = re.sub(r'\bTrue\b', '1', s)
        s = re.sub(r'\bFalse\b', '0', s)
        s = re.sub(r'\bNull\b', 'NULL', s)
        s = re.sub(r'\bThis\b', 'this', s)
        s = re.sub(r'\bNot\b', '!', s)
        s = re.sub(r'\bSizeof\b', 'sizeof', s)
        # Basic standard-library fluent I/O form: cout.expect("fmt").write(args)
        s = re.sub(r'cout\s*\.\s*expect\s*\(\s*("(?:\\.|[^"])*")\s*\)\s*\.\s*write\s*\((.*)\)\s*$',
                   lambda m: 'printf(' + m.group(1) + ((', ' + m.group(2)) if m.group(2).strip() else '') + ')', s)
        s = re.sub(r'cout\s*\.\s*expect\s*\(\s*("(?:\\.|[^"])*")\s*\)\s*\.\s*\((.*)\)\s*$',
                   lambda m: 'printf(' + m.group(1) + ((', ' + m.group(2)) if m.group(2).strip() else '') + ')', s)
        s = re.sub(r'cin\s*\.\s*expect\s*\(\s*("(?:\\.|[^"])*")\s*\)\s*\.\s*read\s*\((.*)\)\s*$',
                   lambda m: 'scanf(' + m.group(1) + ((', ' + m.group(2)) if m.group(2).strip() else '') + ')', s)
        s = re.sub(r'\bSys\s*::\s*Stdio\s*::\s*println\s*\(', 'printf(', s)
        s = re.sub(r'\bSys\s*::\s*Stdio\s*::\s*print\s*\(', 'printf(', s)
        s = re.sub(r'\bSys\s*::\s*Logging\s*::\s*info\s*\(', 'cmotive_sys_logging_info(', s)
        s = re.sub(r'\bSys\s*::\s*Logging\s*::\s*error\s*\(', 'cmotive_sys_logging_error(', s)
        s = re.sub(r'\b([A-Za-z_]\w*)\s*>>>\s*([A-Za-z_0-9]+)\b', r'CMOTIVE_ROTR64(\1, \2)', s)
        s = re.sub(r'\b([A-Za-z_]\w*)\s*<<<\s*([A-Za-z_0-9]+)\b', r'CMOTIVE_ROTL64(\1, \2)', s)
        s = re.sub(r'\bNew\s+([A-Za-z_]\w*)\s*\(([^)]*)\)', lambda m: f'CMotive_New(sizeof({m.group(1)}))', s)
        s = re.sub(r'\bNew\s*\(([^)]*)\)', 'CMotive_New(sizeof(CMotiveObject))', s)
        s = re.sub(r'\bDelete\s+([A-Za-z_]\w*)', r'CMotive_Delete(\1)', s)
        # Default values in CMotive may use integer suffixes valid in CMotive but
        # not all C front-ends; keep the common suffixes but strip long-double D.
        s = re.sub(r'([0-9])D\b', r'\1L', s)
        return s

    def translate_keywords(self, s):
        replacements = {
            'Switch':'switch','Case':'case','Default':'default','Break':'break','Continue':'continue',
            'If':'if','Else':'else','Elif':'else if','While':'while','For':'for','Do':'do',
            'Return':'return','Goto':'goto'
        }
        for k, v in replacements.items():
            s = re.sub(r'\b' + k + r'\b', v, s)
        return s
