from dataclasses import dataclass
import copy
import re
from .ast import (
    Function, ClassDecl, Field, VarDecl, Return, ExprStmt, If, While, DoWhile,
    For, Break, Continue, Throw, TryCatch, RawStmt, PackageDecl, PluginDecl,
    TemplateDecl, BlendDecl, RawDecl, Param
)

@dataclass
class CodegenUnit:
    c_source: str
    target_arch: str

TYPE_MAP = {
    'Boolean':'int','boolean':'int','Bool':'int',
    'Char':'char','char':'char','Char16':'uint16_t','Char32':'uint32_t','Uchar':'unsigned char',
    'I16':'int16_t','I32':'int32_t','Int':'int32_t','I64':'int64_t',
    'U16':'uint16_t','U32':'uint32_t','U64':'uint64_t',
    'Float':'float','Double':'double','Ldouble':'long double',
    'Void':'void','void':'void','Type':'void*','Dynamic':'void*',
}

DEFAULT_PACKAGE = 'StartPackage'

class NativeCodegen:
    def __init__(self, target_arch='native'):
        self.target_arch = target_arch
        self.known_classes = set()
        self.known_functions = set()
        self.templates = {}
        self.class_instances = {}
        self.function_instances = {}
        self.template_use_queue = []
        self.template_use_seen = set()
        self.class_map = {}
        self.functions_by_name = {}
        self.current_package_context = DEFAULT_PACKAGE
        self.ctor_arg_counts = {}
        self._try_id = 0

    def emit(self, program, sema):
        self.templates = {d.name: d for d in program.declarations if isinstance(d, TemplateDecl) and d.name}
        regular_classes = [d for d in program.declarations if isinstance(d, ClassDecl)]
        regular_functions = [d for d in program.declarations if isinstance(d, Function)]
        regular_globals = [d for d in program.declarations if isinstance(d, VarDecl) and d.global_decl]

        self.scan_decls(program.declarations)
        self.instantiate_all()

        all_classes = regular_classes + list(self.class_instances.values())
        self.ensure_lifecycle_methods(all_classes)
        all_classes = self.order_classes_by_base(all_classes)

        all_functions = regular_functions + list(self.function_instances.values())
        # Emit main after helpers/template specializations so C compilers do not
        # see template-specialized calls before their definitions.
        all_functions = [f for f in all_functions if not (f.name == 'main' and not f.method_of)] + [f for f in all_functions if f.name == 'main' and not f.method_of]

        self.class_map = {}
        for c in all_classes:
            self.class_map[c.name] = c
            self.class_map[self.safe_name(c.name)] = c
        self.known_classes = set(self.class_map.keys())
        self.functions_by_name = {}
        for d in all_functions:
            if not d.method_of and d.name != 'main':
                self.functions_by_name.setdefault(d.name, []).append(d)
                self.functions_by_name.setdefault(self.safe_name(d.name), []).append(d)
        self.known_functions = set(self.functions_by_name.keys())
        self.ctor_arg_counts = self.collect_ctor_arg_counts(all_classes)

        out = [
            '/* Generated by CMotive native codegen. */',
            f'/* target-arch: {self.target_arch} */',
            '#include <stdio.h>', '#include <stdlib.h>', '#include <stdint.h>', '#include <stddef.h>',
            '#include <string.h>', '#include <errno.h>', '#include <setjmp.h>', '',
            'typedef struct CMotiveVTable { void **slots; size_t count; } CMotiveVTable;',
            'typedef struct CMotiveObject { CMotiveVTable *vtable; } CMotiveObject;',
            'typedef struct CMotive_ExceptionFrame { jmp_buf env; const char *message; struct CMotive_ExceptionFrame *prev; } CMotive_ExceptionFrame;',
            'static CMotive_ExceptionFrame *__cmotive_exception_stack = NULL;',
            'static void* CMotive_New(size_t n) { return calloc(1, n ? n : 1); }',
            'static void CMotive_Delete(void* p) { free(p); }',
            'static void CMotive_Throw(const char* msg) {',
            '  CMotive_ExceptionFrame *f = __cmotive_exception_stack;',
            '  if (!f) { fprintf(stderr, "CMotive unhandled exception: %s\\n", msg ? msg : "<null>"); exit(70); }',
            '  f->message = msg ? msg : "CMotive exception";',
            '  longjmp(f->env, 1);',
            '}',
            '#define CMOTIVE_EXCEPTION_POP(frameptr) do { if (__cmotive_exception_stack == (frameptr)) __cmotive_exception_stack = (frameptr)->prev; } while (0)',
            'static uint64_t CMOTIVE_ROTR64(uint64_t x, unsigned n) { n &= 63u; return n ? ((x >> n) | (x << (64u - n))) : x; }',
            'static uint64_t CMOTIVE_ROTL64(uint64_t x, unsigned n) { n &= 63u; return n ? ((x << n) | (x >> (64u - n))) : x; }',
            'static int cmotive_sys_file_exists(const char* p) { FILE *f = fopen(p, "rb"); if (!f) return 0; fclose(f); return 1; }',
            'static int cmotive_sys_logging_info(const char* m) { return fprintf(stdout, "%s\\n", m ? m : ""); }',
            'static int cmotive_sys_logging_error(const char* m) { return fprintf(stderr, "%s\\n", m ? m : ""); }',
            ''
        ]
        for d in all_classes:
            out += self.class_decl(d)
        out += self.prototype_block(all_functions, all_classes)
        for d in regular_globals:
            out += self.global_var(d)
        for d in all_functions:
            if not d.pure_virtual:
                out += self.function(d)
        for c in all_classes:
            for m in c.methods:
                if not m.pure_virtual:
                    out += self.function(m)
            out += self.new_delete_helpers(c)
        if not any(isinstance(d, Function) and d.name == 'main' and not d.method_of for d in regular_functions):
            out += ['int main(void) { return 0; }', '']
        return CodegenUnit('\n'.join(out) + '\n', self.target_arch)

    # ---------- template instantiation ----------
    def scan_decls(self, decls):
        for d in decls:
            self.scan_node(d)

    def scan_node(self, node):
        if isinstance(node, TemplateDecl):
            return
        if isinstance(node, ClassDecl):
            if node.base: self.scan_text(node.base)
            for b, _ in node.bases: self.scan_text(b)
            for f in node.fields:
                self.scan_text(f.type_name); self.scan_text(f.initial or '')
            for m in node.methods: self.scan_node(m)
            for n in node.nested: self.scan_node(n)
        elif isinstance(node, Function):
            self.scan_text(node.return_type)
            for p in node.params:
                self.scan_text(p.type_name); self.scan_text(p.default or '')
            for s in node.body: self.scan_node(s)
        elif isinstance(node, VarDecl):
            self.scan_text(node.type_name); self.scan_text(node.value or '')
        elif isinstance(node, Return): self.scan_text(node.value)
        elif isinstance(node, ExprStmt): self.scan_text(node.value)
        elif isinstance(node, If):
            self.scan_text(node.condition); self.scan_decls(node.then_body); self.scan_decls(node.else_body)
        elif isinstance(node, While): self.scan_text(node.condition); self.scan_decls(node.body)
        elif isinstance(node, DoWhile): self.scan_text(node.condition); self.scan_decls(node.body)
        elif isinstance(node, For): self.scan_text(node.header); self.scan_decls(node.body)
        elif isinstance(node, Throw): self.scan_text(node.value)
        elif isinstance(node, TryCatch):
            self.scan_decls(node.try_body)
            for spec, body in node.catches:
                self.scan_text(spec); self.scan_decls(body)
        elif isinstance(node, RawStmt): self.scan_text(node.value)
        elif isinstance(node, RawDecl): self.scan_text(node.value)

    def scan_text(self, text):
        if not text:
            return
        for name, args in self.find_template_uses(str(text)):
            if name in self.templates:
                key = (name, tuple(args))
                if key not in self.template_use_seen:
                    self.template_use_seen.add(key)
                    self.template_use_queue.append(key)

    def find_template_uses(self, text):
        uses = []
        for m in re.finditer(r'\b([A-Za-z_]\w*)\s*<\s*([^<>]+?)\s*>', text):
            name = m.group(1)
            args = self.split_template_args(m.group(2))
            if args:
                uses.append((name, args))
        return uses

    def split_template_args(self, arg_text):
        args, cur, depth = [], [], 0
        for ch in arg_text:
            if ch == '<': depth += 1
            elif ch == '>': depth -= 1
            if ch == ',' and depth == 0:
                val = ''.join(cur).strip()
                if val: args.append(val)
                cur = []
            else:
                cur.append(ch)
        val = ''.join(cur).strip()
        if val: args.append(val)
        return args

    def instantiate_all(self):
        while self.template_use_queue:
            name, args = self.template_use_queue.pop(0)
            templ = self.templates.get(name)
            if not templ or len(args) != len(templ.params):
                continue
            if templ.kind == 'class' and templ.body_node:
                inst_name = self.template_instance_name(name, args)
                if inst_name in self.class_instances:
                    continue
                mapping = {p.name: a for p, a in zip(templ.params, args)}
                cls = self.clone_class_template(templ.body_node, inst_name, mapping)
                self.class_instances[inst_name] = cls
                self.scan_node(cls)
            elif templ.kind == 'function' and templ.body_node:
                inst_name = self.template_instance_name(name, args)
                if inst_name in self.function_instances:
                    continue
                mapping = {p.name: a for p, a in zip(templ.params, args)}
                fn = self.clone_function_template(templ.body_node, inst_name, mapping)
                self.function_instances[inst_name] = fn
                self.scan_node(fn)

    def template_instance_name(self, name, args):
        return self.safe_name(name) + '__' + '__'.join(self.safe_name(self.canonical_type_for_symbol(a)) for a in args)

    def canonical_type_for_symbol(self, t):
        t = self.normalize_template_text(t)
        t = t.replace('::', '_')
        t = re.sub(r'\s+', '', t)
        t = t.replace('*', 'Ptr').replace('&', 'Ref')
        t = t.replace('<', '__').replace('>', '').replace(',', '__')
        return t or 'Type'

    def normalize_template_text(self, t):
        return re.sub(r'\s+', ' ', str(t or '').strip())

    def substitute_type(self, t, mapping):
        s = str(t or '')
        for k, v in mapping.items():
            s = re.sub(r'\b' + re.escape(k) + r'\b', v, s)
        return s

    def substitute_expr(self, text, mapping):
        return self.substitute_type(text, mapping)

    def clone_class_template(self, cls, inst_name, mapping):
        fields = []
        for f in cls.fields:
            nf = copy.copy(f)
            nf.type_name = self.substitute_type(f.type_name, mapping)
            nf.initial = self.substitute_expr(f.initial, mapping) if f.initial is not None else None
            fields.append(nf)
        methods = []
        for m in cls.methods:
            nm = self.clone_function_template(m, m.name, mapping)
            nm.method_of = inst_name
            methods.append(nm)
        nested = [self.clone_class_template(n, inst_name + '__' + n.name, mapping) for n in cls.nested]
        bases = [(self.substitute_type(b, mapping), v) for b, v in cls.bases]
        base = self.substitute_type(cls.base, mapping) if cls.base else None
        return ClassDecl(inst_name, base, methods, fields, cls.has_virtuals, bases, nested, getattr(cls, 'package', DEFAULT_PACKAGE))

    def clone_function_template(self, fn, inst_name, mapping):
        params = [Param(p.name, self.substitute_type(p.type_name, mapping), self.substitute_expr(p.default, mapping) if p.default else None) for p in fn.params]
        body = [self.clone_stmt(s, mapping) for s in fn.body]
        return Function(inst_name, params, body, self.substitute_type(fn.return_type, mapping), fn.method_of, list(fn.decorators), fn.constructor, fn.destructor, fn.pure_virtual, getattr(fn, 'package', DEFAULT_PACKAGE))

    def clone_stmt(self, s, mapping):
        if isinstance(s, VarDecl):
            ns = copy.copy(s); ns.type_name = self.substitute_type(s.type_name, mapping); ns.value = self.substitute_expr(s.value, mapping); return ns
        if isinstance(s, Return): return Return(self.substitute_expr(s.value, mapping))
        if isinstance(s, ExprStmt): return ExprStmt(self.substitute_expr(s.value, mapping))
        if isinstance(s, If): return If(self.substitute_expr(s.condition, mapping), [self.clone_stmt(x, mapping) for x in s.then_body], [self.clone_stmt(x, mapping) for x in s.else_body])
        if isinstance(s, While): return While(self.substitute_expr(s.condition, mapping), [self.clone_stmt(x, mapping) for x in s.body])
        if isinstance(s, DoWhile): return DoWhile([self.clone_stmt(x, mapping) for x in s.body], self.substitute_expr(s.condition, mapping))
        if isinstance(s, For): return For(self.substitute_expr(s.header, mapping), [self.clone_stmt(x, mapping) for x in s.body])
        if isinstance(s, Throw): return Throw(self.substitute_expr(s.value, mapping))
        if isinstance(s, TryCatch): return TryCatch([self.clone_stmt(x, mapping) for x in s.try_body], [(self.substitute_expr(spec, mapping), [self.clone_stmt(x, mapping) for x in body]) for spec, body in s.catches])
        if isinstance(s, RawStmt): return RawStmt(self.substitute_expr(s.value, mapping))
        return copy.copy(s)

    # ---------- lifecycle and class metadata ----------
    def ensure_lifecycle_methods(self, classes):
        for c in classes:
            has_zero_ctor = any(m.constructor and len(m.params) == 0 for m in c.methods)
            if not has_zero_ctor:
                c.methods.insert(0, Function(c.name, [], [], 'Void', c.name, constructor=True, package=getattr(c, 'package', DEFAULT_PACKAGE)))
            if not any(m.destructor for m in c.methods):
                c.methods.append(Function('~' + c.name, [], [], 'Void', c.name, destructor=True, package=getattr(c, 'package', DEFAULT_PACKAGE)))
            for m in c.methods:
                if not getattr(m, 'package', None):
                    m.package = getattr(c, 'package', DEFAULT_PACKAGE)
            for n in c.nested:
                self.ensure_lifecycle_methods([n])

    def order_classes_by_base(self, classes):
        pending = list(classes)
        emitted = set()
        ordered = []
        while pending:
            moved = False
            next_pending = []
            for c in pending:
                b = self.safe_name(c.base) if c.base else None
                if not b or b in emitted or c.base not in {x.name for x in classes} and b not in {self.safe_name(x.name) for x in classes}:
                    ordered.append(c)
                    emitted.add(self.safe_name(c.name))
                    moved = True
                else:
                    next_pending.append(c)
            if not moved:
                ordered.extend(next_pending)
                break
            pending = next_pending
        return ordered

    def collect_ctor_arg_counts(self, classes):
        counts = {}
        for c in classes:
            cname = self.safe_name(c.name)
            counts[cname] = set()
            for m in c.methods:
                if m.constructor:
                    counts[cname].add(len(m.params))
        return counts

    # ---------- C emission ----------
    def class_decl(self, c):
        cname = self.safe_name(c.name)
        lines = [f'typedef struct {cname} {{']
        if c.base:
            bname = self.safe_name(c.base)
            lines.append(f'  {bname} __base;')
        else:
            lines.append('  CMotiveObject __cmotive_object;')
        for f in c.fields:
            lines += self.field_decl(f)
        if c.has_virtuals:
            lines.append('  CMotiveVTable *__cmotive_vtable;')
        lines += [f'}} {cname};', '']
        for n in c.nested:
            lines += self.class_decl(n)
        return lines

    def field_decl(self, f):
        if getattr(f, 'bit_fields', None):
            bits = ['  struct {']
            for count, name in f.bit_fields:
                bits.append(f'    unsigned int {self.safe_name(name)}:{int(count)};')
            bits.append(f'  }} {self.safe_name(f.name)};')
            return bits
        return ['  ' + self.c_decl(f.type_name, self.safe_name(f.name)) + ';']

    def prototype_block(self, free_functions, classes):
        lines = []
        seen = set()
        for f in free_functions:
            if f.pure_virtual:
                continue
            proto = self.function_signature(f) + ';'
            if proto not in seen:
                lines.append(proto); seen.add(proto)
        for c in classes:
            for m in c.methods:
                if m.pure_virtual:
                    continue
                proto = self.function_signature(m) + ';'
                if proto not in seen:
                    lines.append(proto); seen.add(proto)
            for m in [x for x in c.methods if x.constructor]:
                proto = self.new_helper_signature(c, m) + ';'
                if proto not in seen:
                    lines.append(proto); seen.add(proto)
            dproto = self.delete_helper_signature(c) + ';'
            if dproto not in seen:
                lines.append(dproto); seen.add(dproto)
        return lines + [''] if lines else []

    def global_var(self, v):
        prev = self.current_package_context
        self.current_package_context = getattr(v, 'package', DEFAULT_PACKAGE)
        try:
            return [self.c_decl(v.type_name, self.safe_name(v.name)) + ' = ' + self.expr(v.value, v.type_name) + ';', '']
        finally:
            self.current_package_context = prev

    def safe_name(self, name):
        if not name:
            return '_cmotive_unnamed'
        name = str(name).replace('$','__')
        name = name.replace('::', '_')
        name = re.sub(r'\W', '_', name)
        name = name.strip('_') or '_cmotive_unnamed'
        if name in {'class','struct','void','int','long','short','switch','case','default','if','else','while','for','do','return','break','continue'}:
            return 'cmotive_' + name
        return name

    def package_name(self, package=None):
        return self.safe_name(package or DEFAULT_PACKAGE)

    def lookup_class(self, class_name):
        if not class_name:
            return None
        return self.class_map.get(class_name) or self.class_map.get(self.safe_name(class_name))

    def class_package(self, class_name, fallback=None):
        cls = self.lookup_class(class_name)
        return getattr(cls, 'package', None) or fallback or DEFAULT_PACKAGE

    def class_symbol_prefix(self, class_name, package=None):
        return f'{self.package_name(package or self.class_package(class_name))}__{self.safe_name(class_name)}'

    def method_name(self, class_name, method_name, package=None):
        return f'{self.class_symbol_prefix(class_name, package)}__{self.safe_name(method_name)}'

    def constructor_name(self, class_name, argc, package=None):
        base = f'{self.class_symbol_prefix(class_name, package)}__ctor'
        return base if argc == 0 else f'{base}__{argc}'

    def new_name(self, class_name, argc, package=None):
        base = f'{self.class_symbol_prefix(class_name, package)}__new'
        return base if argc == 0 else f'{base}__{argc}'

    def destructor_name(self, class_name, package=None):
        return f'{self.class_symbol_prefix(class_name, package)}__dtor'

    def delete_name(self, class_name, package=None):
        return f'{self.class_symbol_prefix(class_name, package)}__delete'

    def c_name(self, f):
        if f.name == 'main' and not f.method_of:
            return 'main'
        pkg = getattr(f, 'package', DEFAULT_PACKAGE)
        if f.constructor:
            return self.constructor_name(f.method_of or f.name, len(f.params), pkg)
        if f.destructor:
            return self.destructor_name(f.method_of or f.name, pkg)
        if f.method_of:
            return self.method_name(f.method_of, f.name, pkg)
        return f'{self.package_name(pkg)}__{self.safe_name(f.name)}'

    def c_decl(self, type_name, name):
        base, suffix = self.split_array_type(type_name)
        ctype = self.c_type(base)
        return f'{ctype} {name}{suffix}'

    def split_array_type(self, type_name):
        t = type_name or 'I32'
        arrays = ''.join(re.findall(r'\[[^\]]*\]', t))
        t = re.sub(r'\s*\[[^\]]*\]', '', t).strip()
        return t, arrays

    def normalize_type_string(self, t):
        s = str(t or '').strip()
        s = s.replace(' :: ', '::')
        s = re.sub(r'\s*::\s*', '::', s)
        s = re.sub(r'\s*<\s*', '<', s)
        s = re.sub(r'\s*>\s*', '>', s)
        s = re.sub(r'\s*,\s*', ',', s)
        s = re.sub(r'\s*\*\s*', '*', s)
        s = re.sub(r'\s*&\s*', '&', s)
        return s

    def type_template_to_c(self, t):
        s = self.normalize_type_string(t)
        pattern = re.compile(r'\b([A-Za-z_]\w*)<([^<>]+)>')
        while True:
            m = pattern.search(s)
            if not m:
                break
            name = m.group(1); args = self.split_template_args(m.group(2))
            inst = self.template_instance_name(name, args)
            s = s[:m.start()] + inst + s[m.end():]
        return s

    def c_type(self, type_name):
        if not type_name:
            return 'int32_t'
        t = self.type_template_to_c(type_name)
        t = re.sub(r'\bConst\b', 'const', t)
        t = re.sub(r'\bVolatile\b', 'volatile', t)
        ptr = ''
        while t.endswith('*') or t.endswith('&'):
            ptr = ('*' if t[-1] == '*' else '*') + ptr
            t = t[:-1].strip()
        t = t.replace(' :: ', '::').replace('::', '_')
        parts = t.split()
        mapped = []
        for p in parts:
            mapped.append(TYPE_MAP.get(p, p))
        base = ' '.join(mapped) if mapped else 'int32_t'
        if base == 'void' and ptr:
            return 'void ' + ptr
        return (base + (' ' + ptr if ptr else '')).strip()

    def class_type_info(self, type_name):
        t = self.normalize_type_string(type_name)
        is_ptr = '*' in t or '&' in t
        base = self.c_type(t).replace('*', '').strip()
        return base, is_ptr, base in self.known_classes

    def function_signature(self, f):
        ret = 'void' if f.constructor or f.destructor else self.c_type(f.return_type)
        if f.name == 'main' and not f.method_of:
            ret = 'int'
        params = []
        if f.method_of:
            params.append(f'{self.safe_name(f.method_of)} *this')
        for p in f.params:
            params.append(self.c_decl(p.type_name, self.safe_name(p.name)))
        param_text = ', '.join(params) if params else 'void'
        return f'{ret} {self.c_name(f)}({param_text})'

    def function(self, f):
        prev_pkg = self.current_package_context
        self.current_package_context = getattr(f, 'package', DEFAULT_PACKAGE)
        try:
            sig = self.function_signature(f)
            ret = sig.split(' ', 1)[0]
            lines = [sig + ' {']
            scope = {}
            current_class = self.safe_name(f.method_of) if f.method_of else None
            if f.method_of:
                scope['this'] = self.safe_name(f.method_of) + '*'
            for p in f.params:
                scope[self.safe_name(p.name)] = p.type_name
                scope[p.name] = p.type_name
            if f.constructor:
                lines += ['  ' + x for x in self.constructor_prelude(f, scope)]
            for s in f.body:
                lines += ['  ' + x for x in self.stmt(s, [], scope, current_class)]
            if f.destructor:
                lines += ['  ' + x for x in self.destructor_postlude(f)]
            if not any(isinstance(s, Return) for s in f.body):
                if ret == 'void': lines.append('  return;')
                else: lines.append('  return 0;')
            lines += ['}', '']
            return lines
        finally:
            self.current_package_context = prev_pkg

    def constructor_prelude(self, f, scope):
        cls = self.class_map.get(self.safe_name(f.method_of or f.name))
        lines = []
        if cls and cls.base:
            b = self.safe_name(cls.base)
            if 0 in self.ctor_arg_counts.get(b, {0}):
                lines.append(f'{self.constructor_name(b, 0)}(&this->__base);')
        if cls:
            for fld in cls.fields:
                if getattr(fld, 'bit_fields', None):
                    continue
                if not fld.initial or fld.initial == '0':
                    continue
                if '[' in (fld.type_name or ''):
                    continue
                lines.append(f'this->{self.safe_name(fld.name)} = {self.expr(fld.initial, fld.type_name, scope, self.safe_name(cls.name))};')
        return lines

    def destructor_postlude(self, f):
        cls = self.class_map.get(self.safe_name(f.method_of or f.name))
        if cls and cls.base:
            return [f'{self.destructor_name(cls.base)}(&this->__base);']
        return []

    def new_helper_signature(self, c, ctor):
        cname = self.safe_name(c.name)
        params = [self.c_decl(p.type_name, self.safe_name(p.name)) for p in ctor.params]
        return f'{cname} *{self.new_name(cname, len(ctor.params))}(' + (', '.join(params) if params else 'void') + ')'

    def delete_helper_signature(self, c):
        cname = self.safe_name(c.name)
        return f'void {self.delete_name(cname)}({cname} *this)'

    def new_delete_helpers(self, c):
        cname = self.safe_name(c.name)
        lines = []
        seen = set()
        for ctor in [m for m in c.methods if m.constructor]:
            argc = len(ctor.params)
            if argc in seen:
                continue
            seen.add(argc)
            args_decl = [self.c_decl(p.type_name, self.safe_name(p.name)) for p in ctor.params]
            args_call = ', '.join([self.safe_name(p.name) for p in ctor.params])
            if args_call:
                args_call = ', ' + args_call
            sig = f'{cname} *{self.new_name(cname, argc)}(' + (', '.join(args_decl) if args_decl else 'void') + ')'
            lines += [sig + ' {', f'  {cname} *this = ({cname}*)CMotive_New(sizeof({cname}));', '  if (!this) return NULL;', f'  {self.constructor_name(cname, argc)}(this{args_call});', '  return this;', '}', '']
        lines += [self.delete_helper_signature(c) + ' {', '  if (!this) return;', f'  {self.destructor_name(cname)}(this);', '  CMotive_Delete(this);', '}', '']
        return lines

    def stmt(self, s, cleanup=None, scope=None, current_class=None):
        cleanup = cleanup or []
        scope = scope if scope is not None else {}
        if isinstance(s, VarDecl): return self.local_var(s, scope, current_class)
        if isinstance(s, Return):
            lines = [f'CMOTIVE_EXCEPTION_POP({fr});' for fr in reversed(cleanup)]
            lines.append(f'return {self.expr(s.value, scope=scope, current_class=current_class)};' if s.value else 'return;')
            return lines
        if isinstance(s, ExprStmt): return [self.expr_stmt(s.value, scope, current_class)]
        if isinstance(s, If):
            out = [f'if ({self.expr(s.condition, scope=scope, current_class=current_class)}) {{']
            for x in s.then_body: out += ['  ' + y for y in self.stmt(x, cleanup, scope, current_class)]
            out.append('}')
            if s.else_body:
                out.append('else {')
                for x in s.else_body: out += ['  ' + y for y in self.stmt(x, cleanup, scope, current_class)]
                out.append('}')
            return out
        if isinstance(s, While):
            out = [f'while ({self.expr(s.condition, scope=scope, current_class=current_class)}) {{']
            for x in s.body: out += ['  ' + y for y in self.stmt(x, cleanup, scope, current_class)]
            out.append('}')
            return out
        if isinstance(s, DoWhile):
            out = ['do {']
            for x in s.body: out += ['  ' + y for y in self.stmt(x, cleanup, scope, current_class)]
            out.append(f'}} while ({self.expr(s.condition, scope=scope, current_class=current_class)});')
            return out
        if isinstance(s, For):
            out = [f'for ({self.expr(s.header, scope=scope, current_class=current_class)}) {{']
            for x in s.body: out += ['  ' + y for y in self.stmt(x, cleanup, scope, current_class)]
            out.append('}')
            return out
        if isinstance(s, Break): return ['break;']
        if isinstance(s, Continue): return ['continue;']
        if isinstance(s, Throw): return [f'CMotive_Throw({self.stringish(s.value, scope, current_class)});']
        if isinstance(s, TryCatch): return self.try_catch(s, cleanup, scope, current_class)
        if isinstance(s, RawStmt): return [self.raw_stmt(s.value, scope, current_class)]
        return ['/* unknown CMotive statement */']

    def try_catch(self, s, cleanup, scope, current_class):
        self._try_id += 1
        n = self._try_id
        frame = f'&__cmotive_ex_{n}'
        out = [
            '{',
            f'  CMotive_ExceptionFrame __cmotive_ex_{n};',
            f'  __cmotive_ex_{n}.message = NULL;',
            f'  __cmotive_ex_{n}.prev = __cmotive_exception_stack;',
            f'  __cmotive_exception_stack = &__cmotive_ex_{n};',
            f'  int __cmotive_ex_code_{n} = setjmp(__cmotive_ex_{n}.env);',
            f'  if (__cmotive_ex_code_{n} == 0) {{'
        ]
        for x in s.try_body:
            out += ['    ' + y for y in self.stmt(x, cleanup + [frame], scope, current_class)]
        out += [f'    CMOTIVE_EXCEPTION_POP(&__cmotive_ex_{n});', '  } else {', f'    CMOTIVE_EXCEPTION_POP(&__cmotive_ex_{n});', f'    const char *__cmotive_exception_{n} = __cmotive_ex_{n}.message ? __cmotive_ex_{n}.message : "CMotive exception";', f'    int __cmotive_handled_{n} = 0;']
        if s.catches:
            for spec, body in s.catches:
                cond = '1'
                out.append(f'    if (!__cmotive_handled_{n} && ({cond})) {{')
                out.append(f'      __cmotive_handled_{n} = 1;')
                out.append(f'      (void)__cmotive_exception_{n};')
                for x in body:
                    out += ['      ' + y for y in self.stmt(x, cleanup, scope, current_class)]
                out.append('    }')
        out += [f'    if (!__cmotive_handled_{n}) CMotive_Throw(__cmotive_exception_{n});', '  }', '}']
        return out

    def local_var(self, s, scope, current_class):
        name = self.safe_name(s.name)
        typ = s.type_name or 'I32'
        init = (s.value or '0').strip()
        scope[name] = typ
        scope[s.name] = typ
        ctyp = self.c_type(typ)
        base_typ, is_ptr, is_class = self.class_type_info(typ)
        if re.search(r'\bNew\b', init):
            if is_class:
                if is_ptr:
                    return [f'{self.c_decl(typ, name)} = {self.lower_new_expression(init, typ, scope, current_class)};']
                args = self.extract_new_args(init)[1] if self.extract_new_args(init) else ''
                call = self.call_constructor_for_stack(base_typ, name, args)
                return [f'{self.c_decl(typ, name)} = {{0}};'] + ([call] if call else [])
            return [f'{self.c_decl(typ, name)} = ({ctyp})CMotive_New(sizeof(CMotiveObject));']
        if is_class and not is_ptr:
            lines = [f'{self.c_decl(typ, name)} = {{0}};']
            call = self.call_constructor_for_stack(base_typ, name, '')
            if call:
                lines.append(call)
            return lines
        if is_class and is_ptr and init in {'', '0'}:
            return [f'{self.c_decl(typ, name)} = NULL;']
        return [f'{self.c_decl(typ, name)} = {self.expr(init, typ, scope, current_class)};']

    def call_constructor_for_stack(self, cls, var_name, args):
        argc = self.count_call_args(args)
        cname = self.safe_name(cls)
        if argc not in self.ctor_arg_counts.get(cname, set()):
            argc = 0
            args = ''
        if argc == 0:
            return f'{self.constructor_name(cname, 0)}(&{var_name});'
        return f'{self.constructor_name(cname, argc)}(&{var_name}, {self.expr(args)});'

    def extract_new_args(self, text):
        s = self.normalize_type_string(text)
        m = re.search(r'\bNew\s+([A-Za-z_]\w*(?:<[^<>]+>)?)\s*\((.*)\)\s*$', s)
        if m:
            return self.c_type(m.group(1)).replace('*', '').strip(), m.group(2).strip()
        m = re.search(r'\bNew\s*\((.*)\)\s*$', s)
        if m:
            return None, m.group(1).strip()
        return None

    def lower_new_expression(self, text, declared_type=None, scope=None, current_class=None):
        parsed = self.extract_new_args(text)
        if not parsed:
            return self.expr(text, declared_type, scope, current_class)
        explicit_cls, args = parsed
        declared_base, declared_ptr, declared_is_class = self.class_type_info(declared_type or '')
        cls = explicit_cls or (declared_base if declared_is_class else None)
        if not cls or cls not in self.known_classes:
            return f'CMotive_New(sizeof({cls or "CMotiveObject"}))'
        argc = self.count_call_args(args)
        if argc not in self.ctor_arg_counts.get(cls, set()):
            argc = 0
            args = ''
        call = f'{self.new_name(cls, argc)}(' + (self.expr(args, scope=scope, current_class=current_class) if args else '') + ')'
        if declared_is_class and declared_base != cls:
            return f'({self.c_type(declared_type)}){call}'
        return call

    def count_call_args(self, arg_text):
        if not arg_text or not str(arg_text).strip():
            return 0
        return len(self.split_expr_args(arg_text))

    def split_expr_args(self, arg_text):
        args, cur, depth, in_str, esc = [], [], 0, False, False
        for ch in str(arg_text):
            if in_str:
                cur.append(ch)
                if esc:
                    esc = False
                elif ch == '\\':
                    esc = True
                elif ch == '"':
                    in_str = False
                continue
            if ch == '"':
                in_str = True; cur.append(ch); continue
            if ch in '([{<': depth += 1
            elif ch in ')]}>': depth -= 1
            if ch == ',' and depth == 0:
                val = ''.join(cur).strip()
                if val: args.append(val)
                cur = []
            else:
                cur.append(ch)
        val = ''.join(cur).strip()
        if val: args.append(val)
        return args

    def expr_stmt(self, text, scope=None, current_class=None):
        e = self.expr(text, scope=scope, current_class=current_class)
        if not e or e == ';': return ';'
        return e if e.rstrip().endswith(';') else e + ';'

    def raw_stmt(self, text, scope=None, current_class=None):
        e = self.translate_keywords(text)
        e = self.expr(e, scope=scope, current_class=current_class)
        return e if e.rstrip().endswith(';') or e.rstrip().endswith('}') else e + ';'

    def stringish(self, text, scope=None, current_class=None):
        e = self.expr(text, scope=scope, current_class=current_class)
        if e.startswith('"'):
            return e
        if re.fullmatch(r'[0-9]+', e or ''):
            return '"CMotive numeric exception"'
        return '(const char*)(' + (e or '"CMotive exception"') + ')'

    def cmotive_cast_to_c(self, typename):
        t = typename.strip().replace(' ', '')
        pointer = ''
        while t.endswith('*'):
            pointer += '*'; t = t[:-1]
        mapped = TYPE_MAP.get(t, self.c_type(t))
        if pointer: return mapped + ' ' + pointer
        return mapped

    def lower_typecasts(self, s):
        names = '|'.join(sorted((re.escape(k) for k in TYPE_MAP.keys()), key=len, reverse=True))
        pat = re.compile(r'\(\s*(' + names + r')(\s*\*+)?\s*\)')
        return pat.sub(lambda m: '(' + self.cmotive_cast_to_c((m.group(1) + (m.group(2) or '')).strip()) + ')', s)

    def lower_template_calls(self, s):
        for name, args in self.find_template_uses(s):
            if name in self.templates:
                inst = self.template_instance_name(name, args)
                fn = self.function_instances.get(inst)
                sym = self.c_name(fn) if fn is not None else f'{self.package_name(self.current_package_context)}__{inst}'
                s = re.sub(r'\b' + re.escape(name) + r'\s*<\s*' + re.escape(','.join(args)).replace(',', r'\s*,\s*') + r'\s*>\s*\(', sym + '(', s)
        for (name, args) in list(self.template_use_seen):
            inst = self.template_instance_name(name, list(args))
            fn = self.function_instances.get(inst)
            sym = self.c_name(fn) if fn is not None else f'{self.package_name(self.current_package_context)}__{inst}'
            arg_pat = r'\s*,\s*'.join(re.escape(a).replace('\\ ', r'\s*') for a in args)
            s = re.sub(r'\b' + re.escape(name) + r'\s*<\s*' + arg_pat + r'\s*>\s*\(', sym + '(', s)
        return s

    def resolve_function_symbol(self, name):
        candidates = self.functions_by_name.get(name) or self.functions_by_name.get(self.safe_name(name)) or []
        if not candidates:
            return None
        current_pkg = self.package_name(self.current_package_context)
        for f in candidates:
            if self.package_name(getattr(f, 'package', DEFAULT_PACKAGE)) == current_pkg:
                return self.c_name(f)
        if len(candidates) == 1:
            return self.c_name(candidates[0])
        for f in candidates:
            if self.package_name(getattr(f, 'package', DEFAULT_PACKAGE)) == self.package_name(DEFAULT_PACKAGE):
                return self.c_name(f)
        return self.c_name(candidates[0])

    def lower_known_function_calls(self, s):
        for name in sorted(self.known_functions, key=len, reverse=True):
            safe = self.safe_name(name)
            if not safe or safe == 'main':
                continue
            sym = self.resolve_function_symbol(name)
            if not sym:
                continue
            s = re.sub(r'(?<![\w:.>-])\b' + re.escape(name) + r'\s*\(', sym + '(', s)
        return s

    def lower_method_calls(self, s, scope=None, current_class=None):
        scope = scope or {}
        if current_class:
            for m in self.class_map.get(current_class, ClassDecl(current_class)).methods:
                if m.constructor or m.destructor or m.pure_virtual:
                    continue
                s = re.sub(r'\bthis\s*->\s*' + re.escape(m.name) + r'\s*\(', f'{self.method_name(current_class, m.name)}(this, ', s)
        for var, typ in sorted(scope.items(), key=lambda x: len(x[0]), reverse=True):
            if var == 'this':
                continue
            cls, is_ptr, is_class = self.class_type_info(typ)
            if not is_class:
                continue
            if is_ptr:
                s = re.sub(r'\b' + re.escape(var) + r'\s*->\s*([A-Za-z_]\w*)\s*\(', lambda m: f'{self.method_name(cls, m.group(1))}({var}, ', s)
            else:
                s = re.sub(r'\b' + re.escape(var) + r'\s*\.\s*([A-Za-z_]\w*)\s*\(', lambda m: f'{self.method_name(cls, m.group(1))}(&{var}, ', s)
        s = re.sub(r',\s*\)', ')', s)
        return s

    def lower_member_names(self, s, scope=None, current_class=None):
        if not current_class or current_class not in self.class_map:
            return s
        scope = scope or {}
        cls = self.class_map[current_class]
        local_names = {self.safe_name(k) for k in scope.keys()}
        for fld in cls.fields:
            fname = self.safe_name(fld.name)
            if fname in local_names:
                continue
            s = re.sub(r'(?<![\w.>])\b' + re.escape(fname) + r'\b(?!\s*\()', 'this->' + fname, s)
        return s

    def lower_delete(self, s, scope=None):
        scope = scope or {}
        def repl(m):
            var = self.safe_name(m.group(1))
            typ = scope.get(var) or scope.get(m.group(1)) or ''
            cls, is_ptr, is_class = self.class_type_info(typ)
            if is_class:
                return f'{self.delete_name(cls)}({var})' if is_ptr else f'{self.destructor_name(cls)}(&{var})'
            return f'CMotive_Delete({var})'
        return re.sub(r'\bDelete\s+([A-Za-z_]\w*)', repl, s)

    def expr(self, e, declared_type=None, scope=None, current_class=None):
        if e is None: return ''
        s = str(e).strip()
        if not s: return ''
        s = self.translate_keywords(s)
        s = re.sub(r'\bTrue\b', '1', s)
        s = re.sub(r'\bFalse\b', '0', s)
        s = re.sub(r'\bNull\b', 'NULL', s)
        s = re.sub(r'\bThis\b', 'this', s)
        s = re.sub(r'\bNot\b', '!', s)
        s = re.sub(r'\bSizeof\b', 'sizeof', s)
        s = self.lower_typecasts(s)
        s = re.sub(r'\bthis\s*\.\s*', 'this->', s)
        s = self.lower_template_calls(s)
        s = re.sub(r'cout\s*\.\s*expect\s*\(\s*("(?:\\\\.|[^"])*")\s*\)\s*\.\s*write\s*\((.*)\)\s*$', lambda m: 'printf(' + m.group(1) + ((', ' + m.group(2)) if m.group(2).strip() else '') + ')', s)
        s = re.sub(r'cout\s*\.\s*expect\s*\(\s*("(?:\\\\.|[^"])*")\s*\)\s*\.\s*\((.*)\)\s*$', lambda m: 'printf(' + m.group(1) + ((', ' + m.group(2)) if m.group(2).strip() else '') + ')', s)
        s = re.sub(r'cin\s*\.\s*expect\s*\(\s*("(?:\\\\.|[^"])*")\s*\)\s*\.\s*read\s*\((.*)\)\s*$', lambda m: 'scanf(' + m.group(1) + ((', ' + m.group(2)) if m.group(2).strip() else '') + ')', s)
        s = re.sub(r'\bSys\s*::\s*Stdio\s*::\s*println\s*\(', 'printf(', s)
        s = re.sub(r'\bSys\s*::\s*Stdio\s*::\s*print\s*\(', 'printf(', s)
        s = re.sub(r'\bSys\s*::\s*Logging\s*::\s*info\s*\(', 'cmotive_sys_logging_info(', s)
        s = re.sub(r'\bSys\s*::\s*Logging\s*::\s*error\s*\(', 'cmotive_sys_logging_error(', s)
        s = re.sub(r'\b([A-Za-z_]\w*)\s*>>>\s*([A-Za-z_0-9]+)\b', r'CMOTIVE_ROTR64(\1, \2)', s)
        s = re.sub(r'\b([A-Za-z_]\w*)\s*<<<\s*([A-Za-z_0-9]+)\b', r'CMOTIVE_ROTL64(\1, \2)', s)
        s = self.lower_delete(s, scope)
        if re.search(r'\bNew\b', s):
            parsed = self.extract_new_args(s)
            if parsed and parsed[0] is not None and s.strip().startswith('New'):
                s = self.lower_new_expression(s, declared_type, scope, current_class)
            elif parsed and s.strip().startswith('New'):
                s = self.lower_new_expression(s, declared_type, scope, current_class)
            else:
                s = re.sub(r'\bNew\s+([A-Za-z_]\w*(?:\s*<\s*[^<>]+\s*>)?)\s*\(([^)]*)\)', lambda m: f'{self.new_name(self.c_type(m.group(1)).replace("*", "").strip(), self.count_call_args(m.group(2)))}({m.group(2).strip()})', s)
                s = re.sub(r'\bNew\s*\(([^)]*)\)', 'CMotive_New(sizeof(CMotiveObject))', s)
        s = self.lower_method_calls(s, scope, current_class)
        s = self.lower_member_names(s, scope, current_class)
        s = self.lower_known_function_calls(s)
        s = re.sub(r'([0-9])D\b', r'\1L', s)
        return s

    def translate_keywords(self, s):
        replacements = {
            'Switch':'switch','Case':'case','Default':'default','Break':'break','Continue':'continue',
            'If':'if','Else':'else','Elif':'else if','While':'while','For':'for','Do':'do',
            'Return':'return','Goto':'goto'
        }
        for k, v in replacements.items():
            s = re.sub(r'\b' + k + r'\b', v, s)
        return s
