from dataclasses import dataclass
from .ast import Function, ClassDecl, VarDecl, Return, ExprStmt, If, While
@dataclass
class CodegenUnit: c_source:str; target_arch:str
class NativeCodegen:
    def __init__(self,target_arch='native'): self.target_arch=target_arch
    def emit(self,program,sema):
        out=['/* Generated by CMotive native codegen scaffold. */','#include <stdio.h>','#include <stdlib.h>','#include <stdint.h>','']
        out += ['typedef struct CMotiveVTable { void **slots; size_t count; } CMotiveVTable;','typedef struct CMotiveObject { CMotiveVTable *vtable; } CMotiveObject;','static void* CMotive_New(size_t n) { return calloc(1, n); }','static void CMotive_Delete(void* p) { free(p); }','static void CMotive_Throw(const char* msg) { fprintf(stderr, "CMotive exception: %s\\n", msg); exit(70); }','']
        for d in program.declarations:
            if isinstance(d,ClassDecl): out += self.class_decl(d)
        for d in program.declarations:
            if isinstance(d,Function): out += self.function(d)
            elif isinstance(d,ClassDecl):
                for m in d.methods: out += self.function(m)
        return CodegenUnit('\n'.join(out)+'\n',self.target_arch)
    def class_decl(self,c): return [f'typedef struct {c.name} {{','  CMotiveObject base;',*['  int '+f+';' for f in c.fields],f'}} {c.name};','']
    def cname(self,f): return 'main' if f.name=='main' and not f.method_of else ((f.method_of+'__') if f.method_of else 'cmotive__')+f.name
    def function(self,f):
        params=', '.join('int '+p for p in f.params) or 'void'; lines=[f'int {self.cname(f)}({params}) {{']
        for s in f.body: lines += ['  '+x for x in self.stmt(s)]
        if not any(isinstance(s,Return) for s in f.body): lines.append('  return 0;')
        lines += ['}','']; return lines
    def stmt(self,s):
        if isinstance(s,VarDecl): return [f'int {s.name} = {self.expr(s.value)};']
        if isinstance(s,Return): return [f'return {self.expr(s.value)};']
        if isinstance(s,ExprStmt): return [self.expr(s.value)+';']
        if isinstance(s,If):
            out=[f'if ({self.expr(s.condition)}) {{']
            for x in s.then_body: out += ['  '+y for y in self.stmt(x)]
            out.append('}')
            if s.else_body:
                out.append('else {')
                for x in s.else_body: out += ['  '+y for y in self.stmt(x)]
                out.append('}')
            return out
        if isinstance(s,While):
            out=[f'while ({self.expr(s.condition)}) {{']
            for x in s.body: out += ['  '+y for y in self.stmt(x)]
            out.append('}'); return out
        return ['/* unknown statement */']
    def expr(self,e): return e.replace('Sys :: Stdio :: print','printf').replace('New','CMotive_New').replace('Delete','CMotive_Delete')
